services:
  - type: web
    name: django-web
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn Blog_clone.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: Blog_clone.settings
      - key: SECRET_KEY
        generateValue: true
